In [2]:
import pandas as pd

In [7]:
df = pd.read_csv('../datasets/BostonHousing.csv')

In [9]:
df.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [11]:
import numpy as np

In [12]:
# List vs Numpy - Time Taken

In [13]:
from time import process_time

In [52]:
#Time taken by list

py_ls = [i for i in range(10000)]
start_time = process_time()
py_ls = [i+5 for i in py_ls]
end_time = process_time()
print(end_time-start_time)


0.0009866869999999306


In [55]:
#Time take by Numpy
arr = np.array([i for i in range(10000)])
start_time = process_time()
arr += 5
end_time = process_time()
print(end_time-start_time)

0.00012715800000018262


In [ ]:
#Numpy Arrays

In [56]:
list1 = [1,2,3,4,5]
type(list1)

list

In [57]:
np_arr = np.array([1,2,3,4,5])
type(np_arr)

numpy.ndarray

In [59]:
a = np.array(1,2,3,4)

(5,)

In [60]:
b = np.array([(1,2,3,4),(5,6,7,8)])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [61]:
b.shape

(2, 4)

In [64]:
b2 = np.array([[1,2,3,4],[5,6,7,8]])
b2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [65]:
b2.shape

(2, 4)

In [67]:
c = np.array([[1,2,3,4],[5,6,7,8]],dtype=float)
c

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [68]:
#Initial placeholders

In [69]:
# numpy array of zeros
k = np.zeros((4,5))
k

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [70]:
# numpy array of ones
m = np.ones((3,3))
m

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [71]:
# array of a particular value
z = np.full((5,5),10)
z

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [72]:
# identity matrix
id_m = np.eye(10)
id_m

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [80]:
# numpy with random values
f = np.random.random((3,5))
f

array([[0.34564477, 0.01673486, 0.54996967, 0.433373  , 0.23471423],
       [0.45329967, 0.25402998, 0.37357752, 0.21177068, 0.29792242],
       [0.06526038, 0.44242504, 0.74006686, 0.868166  , 0.05276076]])

In [ ]:
# random integers within a specific range
d = np.random.randint()